# Generated by Django 3.1.7 on 2021-04-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='thumbnail',
        ),
    ]
