# Generated by Django 3.1.7 on 2021-04-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_job_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
    ]
