# Generated by Django 3.1.7 on 2021-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_jobrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_img'),
        ),
    ]
