# Generated by Django 3.1.7 on 2021-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_job_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
