# Generated by Django 3.1.7 on 2021-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_job_application_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
