# Generated by Django 3.1.7 on 2021-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_job_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
