# Generated by Django 3.1.7 on 2021-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210411_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
