# Generated by Django 3.1.7 on 2021-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='featured',
        ),
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
